services:
  db:
    image: postgres
    container_name: gymlifestyle_postgres_container
    environment:
      POSTGRES_DB: gymlifestyledb
      POSTGRES_USER: gymlifestyle
      POSTGRES_PASSWORD: gymlifestyle2024#!
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: